// TODO: move this to server-side

export default {
  "docs.google.com/document/": "OPEN DOC",
  "docs.google.com/presentation/": "OPEN SLIDES",
  "docs.google.com/spreadsheets/": "OPEN SHEET",
  "docs.google.com/forms/": "OPEN FORM",
  "docusign.net/member/": "DOCUSIGN",
  "dropbox.com/l/": "OPEN DROPBOX",
  "drive.google.com/file/": "OPEN DRIVE",
  "we.tl/": "OPEN FILE",
  "teams.microsoft.com/l/meetup-join/": "JOIN MEETING",
  "meet.google.com/": "JOIN MEETING",
  "join.skype.com": "JOIN MEETING",
  ".qualtrics.com/jfe/": "OPEN QUALTRICS",
  "app.asana.com/app": "OPEN ASANA",
  ".sharepoint.com/:": "OPEN DOC",
  "zoom.us/": "JOIN MEETING",
  "evernote.com/i/": "OPEN EVERNOTE",
  ".webex.com/": "JOIN MEETING",
  "trellomail.com": "OPEN TRELLO",
  "app.intercom.io": "OPEN INTERCOM",
  "link.gusto.com": "OPEN GUSTO",
  "dashboard.stripe.com/b/": "OPEN STRIPE",
  "dashboard.stripe.com/confirm_email": "VERIFY STRIPE",
  "dashboard.stripe.com/emails/receipts/": "GET RECEIPT",
  "dashboard.stripe.com/join/": "JOIN STRIPE",
  "dashboard.stripe.com/reset/": "SET PASSWORD",
  "netflix.com/password": "SET PASSWORD",
  "instagram.com/accounts/password": "SET PASSWORD",
  "airbnb.com/messaging/": "OPEN AIRBNB",
  "click-email.godaddy.com/": "OPEN GODADDY",
  "click.e.usa.experian.com/": "OPEN EXPERIAN",
  "calendly.com/": "OPEN CALENDLY",
} as Record<string, string>