// TODO: move this to server-side

export default {
  "docs.google.com/document/": {text: "OPEN DOC", priority: 10},
  "docs.google.com/presentation/": {text: "OPEN SLIDES", priority: 10},
  "docs.google.com/spreadsheets/": {text: "OPEN SHEET", priority: 10},
  "docs.google.com/forms/": {text: "OPEN FORM", priority: 10},
  "docusign.net/member/": {text: "DOCUSIGN", priority: 10},
  "dropbox.com/l/": {text: "OPEN DROPBOX", priority: 10},
  "drive.google.com/file/": {text: "OPEN DRIVE", priority: 10},
  "we.tl/": {text: "OPEN FILE", priority: 0},
  "teams.microsoft.com/l/meetup-join/": {text: "JOIN IN TEAMS", priority: 20},
  "meet.google.com/": {text: "JOIN ON ZOOM", priority: 20},
  "join.skype.com": {text: "JOIN ON SKYPE", priority: 20},
  ".qualtrics.com/jfe/": {text: "OPEN QUALTRICS", priority: 0},
  "app.asana.com/app": {text: "OPEN ASANA", priority: 0},
  ".sharepoint.com/:": {text: "OPEN DOC", priority: 0},
  "zoom.us/j/": {text: "JOIN ON ZOOM", priority: 20},
  "evernote.com/i/": {text: "OPEN EVERNOTE", priority: 0},
  ".webex.com/": {text: "JOIN ON WEBEX", priority: 20},
  "trellomail.com": {text: "OPEN TRELLO", priority: 0},
  "app.intercom.io": {text: "OPEN INTERCOM", priority: 0},
  "link.gusto.com": {text: "OPEN GUSTO", priority: 0},
  "dashboard.stripe.com/b/": {text: "OPEN STRIPE", priority: 0},
  "dashboard.stripe.com/confirm_email": {text: "VERIFY STRIPE", priority: 10},
  "dashboard.stripe.com/emails/receipts/": {text: "GET RECEIPT", priority: 20},
  "dashboard.stripe.com/join/": {text: "JOIN STRIPE", priority: 0},
  "dashboard.stripe.com/reset/": {text: "SET PASSWORD", priority: 10},
  "netflix.com/password": {text: "SET PASSWORD", priority: 0},
  "instagram.com/accounts/password": {text: "SET PASSWORD", priority: 0},
  "airbnb.com/messaging/": {text: "OPEN AIRBNB", priority: 0},
  "click-email.godaddy.com/": {text: "OPEN GODADDY", priority: 0},
  "click.e.usa.experian.com/": {text: "OPEN EXPERIAN", priority: 0},
  "calendly.com/": {text: "OPEN CALENDLY", priority: 1},
} as Record<string, {text: string, priority: number}>