# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ redo ]
  pull_request:
    branches: [ redo ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Status
      run: echo May the Baby Seal\'s blessings be with you.

    - name: Audit with Snyk
      uses: snyk/actions@0.1.1

    - name: Audit with NodeJS Scaan
      uses: ajinabraham/njsscan-action@v5

    - name: Lint with Super-Linter
      uses: github/super-linter@v2.0.0
